### ISSUE TITLE
Enchant

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdla-stats#1]
- [x] Travis-CI https://travis-ci.org/PDLPorters/pdla-stats (https://travis-ci.org/profile/PDLPorters)
- [x] Appveyor CI (https://ci.appveyor.com/project/zmughal/pdla-stats)
- [x] Coveralls https://coveralls.io/r/PDLPorters/pdla-stats (https://coveralls.io/repos/new?name=PDLPorters)
- [x] IRC notifications (handled by devops `enchant` script)

**Comment by mohawk2** [comment]
Is this all done now?

**Comment by zmughal** [comment]
Let me get the remaining Appveyor integration working just now. I will close when it is all done.

**Comment by mohawk2** [comment]
Superb!
